// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIyTI9-KqQUHGbKpUv9VQp7Vf1LazGmOg',
    appId: '1:816680711906:web:fe83b352d30da945ae10bb',
    messagingSenderId: '816680711906',
    projectId: 'b3-learn',
    authDomain: 'b3-learn.firebaseapp.com',
    storageBucket: 'b3-learn.firebasestorage.app',
    measurementId: 'G-SLVD3XJ6Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-LT9a1Skm_vX7lcErHUsPwUe2v4nA8I',
    appId: '1:816680711906:android:ec78aff547144af5ae10bb',
    messagingSenderId: '816680711906',
    projectId: 'b3-learn',
    storageBucket: 'b3-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHb6MPuQn8FkehNUfCQKkNHLCE3ShWS-I',
    appId: '1:816680711906:ios:3e23be22d03ff55cae10bb',
    messagingSenderId: '816680711906',
    projectId: 'b3-learn',
    storageBucket: 'b3-learn.firebasestorage.app',
    iosBundleId: 'com.example.b3Learn',
  );
}
